server:
  port: 8080
  host: 0.0.0.0
  mode: debug
  publicUrl: http://localhost:8080

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: blog
  password: MNGMKf8c3P8teiTC
  database: blog
  autoMigrate: true
  params: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  host: 127.0.0.1
  port: 6379
  password: "redis_QCHytt"
  db: 0

jwt:
  secret: "your-secret-key"
  access_expiry: 3h
  refresh_expiry: 168h # 7 days

logging:
  level: "info"
  file_path: "./logs/app.log"

storage:
  publicPrefix: /uploads
  localPath: ./public/uploads